### ISSUE TITLE
Allow creation of domain names and TLS information without interacting with cluster operator

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/service-apis#103]
**What would you like to be added**:
As an application developer, I want to be able to add arbitrary domain names, including TLS information if required, to a gateway without having access to modify Gateway objects.

As an application developer, I want to be able to expose my service in a shared cluster, using a shared load balancer, using my own custom domain, with TLS information either autogenerated or supplied by me.

I do not want to have to interact in any other way than the API with the cluster operator team.

Contrast this use case with #102.

**Why is this needed**:
We've had some requests come in to Contour for similar functionality, because the HTTPProxy model does not work for them.

This issue is an attempt to capture something like the requirement, although I'm not sure if I got it right.

**Comment by robscott** [comment]
We discussed this during office hours - here's an attempt at summarizing our thoughts:

1. In most cases, users that are configuring TLS will naturally also have access to Gateways.
2. In other cases, TLS config could be implemented with a controller watching Routes and adding generated certs to corresponding Gateways.
3. This does not solve the use case for users wanting to provide their own certs for Routes while not having access to a Gateway resource. This seems like it would be a rare edge case and is not worth supporting at this point. We have outlined a potential solution in the security model that could enable this in the future, but there does not seem to be a sufficient reason to work towards that now.

**Comment by jpeach** [comment]
Maybe another way to approach this would be to think through how the gateway API would work with existing controllers. For example; if we stipulate that cert-manager is operating in the cluster, then step (2) would be a controller that watches Routes, and creates the necessary Certificate resources. Then, we would need to ensure that once the Certificate was provisioned, the corresponding Secret (containing the TLS certificate, key and CA bundle) could be attached to the Route.

So, this approach suggests that the API should deal with TLS certificate in terms of Secrets. We can do similar exercises for other controllers.

**Comment by Miciah** [comment]
> 3\. This does not solve the use case for users wanting to provide their own certs for Routes while not having access to a Gateway resource. This seems like it would be a rare edge case and is not worth supporting at this point. We have outlined a potential solution in the security model that could enable this in the future, but there does not seem to be a sufficient reason to work towards that now.

I think it actually could solve the use case, and this is a critical use case for OpenShift.

Our biggest challenge to adopting Ingress v1 was the secrets problem:  How do you safely enable the ingress controller to read users' secrets so that it can get user-provided certificates?  The ingress controller is a complex piece of software that communicates with untrusted agents, so granting it access to read all secrets in the cluster is out of the question.  At the same time, multi-tenant use cases are critical to us, so we need to allow users to specify certificates (but have no direct control of the ingress controller's configuration), and we need somehow to allow the ingress controller to read the certificates (but not be able to read everybody's secrets).

Our solution was to write a controller that performed one job: read in services and secrets and write out route objects, where a route object has both the routing rules from the ingress and the certificate from the secret.  Then we granted the ingress controller read access to route objects.  In short, we use privilege separation: one relatively simple controller has access to read ingresses and secrets and write routes, and another, more complex controller reads routes, communicates with clients, and forwards to pod endpoints.

Is there a reason why the controller you suggest in your second point couldn't do something similar?  For example, instead of generating certificates, it could copy user-provided certificates to a trusted namespace (see #105).  This controller would only be able to read secrets, gateways, and routes and update gateways.

An alternative would be to use fine-grained RBAC permissions to grant the ingress controller read access to specific secrets (possibly related to #115).  Manually managing those permissions would be a hassle, though, and I'm not sure people would be comfortable with a controller that auto-granted read access to secrets (maybe it is effectively no less secure than a controller that copies secrets around, but it might be a problem for some security policies or auditing processes, for example).

Another alternative would be to eschew secrets and put certificates directly in route objects; I'm not sure whether we have explicitly discussed that option (although it may have been suggested in one of the virtual host design proposals).

**Comment by hbagdi** [comment]
> Our biggest challenge to adopting Ingress v1 was the secrets problem: How do you safely enable the ingress controller to read users' secrets so that it can get user-provided certificates?

This is a very common problem and complain with Kubernetes Ingress. This how I see the current model could solve the problem: Gateways are spun up only in a specific namespace or a set of namespaces. These are RBAC protected so that only few humans have access to it. The controllers responsible for configuring these gateways can now be given read access to secrets in these namespaces in which the Gateway resources are configured. Also, the Gateway resource can point to a TLS secret in the same namespace only. 

Does this help your use-case, Miciah?


> An alternative would be to use fine-grained RBAC permissions to grant the ingress controller read access to specific secrets

I tried doing this but then the controller can't watch Secret resource for changes. If the TLS secret changes, the controller needs to know about it. My current understanding is that the way RBAC in k8s works, to watch a resource, you need a read all permission (cluster-wide or a specific namespace based on what you want to do).

> eschew secrets and put certificates directly in route objects

What about the private key of the certificate? Secrets are used because private keys are sensitive and users want to protect them.

**Comment by jpeach** [comment]
> > 3. This does not solve the use case for users wanting to provide their own certs for Routes while not having access to a Gateway resource. This seems like it would be a rare edge case and is not worth supporting at this point. We have outlined a potential solution in the security model that could enable this in the future, but there does not seem to be a sufficient reason to work towards that now.
> 
> I think it actually could solve the use case, and this is a critical use case for OpenShift.
> 
> Our biggest challenge to adopting Ingress v1 was the secrets problem: How do you safely enable the ingress controller to read users' secrets so that it can get user-provided certificates? The ingress controller is a complex piece of software that communicates with untrusted agents, so granting it access to read all secrets in the cluster is out of the question. At the same time, multi-tenant use cases are critical to us, so we need to allow users to specify certificates (but have no direct control of the ingress controller's configuration), and we need somehow to allow the ingress controller to read the certificates (but not be able to read everybody's secrets).
> 
> Our solution was to write a controller that performed one job: read in services and secrets and write out route objects, where a route object has both the routing rules from the ingress and the certificate from the secret. Then we granted the ingress controller read access to route objects. In short, we use privilege separation: one relatively simple controller has access to read ingresses and secrets and write routes, and another, more complex controller reads routes, communicates with clients, and forwards to pod endpoints.

I like this privilege separation, and I think it's an approach worth exploring. Maybe rather than defining TLS in terms of secrets, we have a specific binding type that we use to interact with TLS provisioning systems. The binding type can also be more structures that a generic secret, which might have some advantages.

**Comment by robscott** [comment]
I like this potential approach as well. I'm interested in what a new binding type @jpeach is describing would look like. Would be nice to have an approach enabling additional use cases like this.

**Comment by Miciah** [comment]
@hbagdi,

> This is a very common problem and complain with Kubernetes Ingress. This how I see the current model could solve the problem: Gateways are spun up only in a specific namespace or a set of namespaces. These are RBAC protected so that only few humans have access to it. The controllers responsible for configuring these gateways can now be given read access to secrets in these namespaces in which the Gateway resources are configured. Also, the Gateway resource can point to a TLS secret in the same namespace only.
> 
> Does this help your use-case, Miciah?

By itself, I don't think it solves the use-case.  If I understand you correctly, you are saying that a gateway controller would have access to read secrets from a specific namespace (or set of namespaces) and would read serving certificates from that namespace (or those namespaces).  A consequence would be that an actor who is configuring the serving certificate for a route would need the ability to create and update secrets in that namespace.  Configuring a route's serving certificate would then become a privileged operation.

You could however resolve the problem by introducing another controller that copied secrets referenced by routes into the gateway's namespace; I was suggesting something like this in https://github.com/kubernetes-sigs/service-apis/issues/103#issuecomment-611772367.

> > An alternative would be to use fine-grained RBAC permissions to grant the ingress controller read access to specific secrets
> 
> I tried doing this but then the controller can't watch Secret resource for changes. If the TLS secret changes, the controller needs to know about it. My current understanding is that the way RBAC in k8s works, to watch a resource, you need a read all permission (cluster-wide or a specific namespace based on what you want to do).

Yeah, that is a problem, and it implies that we must do one of the following: (1) eschew secrets (as described below) or (2) introduce a privileged controller that copies users' secrets into the gateway's namespace (as described above).

> > eschew secrets and put certificates directly in route objects
> 
> What about the private key of the certificate? Secrets are used because private keys are sensitive and users want to protect them.

If you use a different resource, you can grant the gateway controller cluster-wide get/list/watch access to that resource, grant users full access to the resource within their respective namespaces, and otherwise prohibit access to the resource.  This approach is clear and easy to understand, grants exactly the permission to exactly who should have it, and avoids compromising secrets (because the approach does not add any RBAC rules related to secrets).

**Comment by youngnick** [comment]
The way Contour solves this exact problem is with a TLSDelegation CRD: this lives in the same namespace as a Secret and allows a HTTPProxy object in a namespace (given by a list with globbing) to reference a Secret without the owner of the HTTPProxy object being able to see the Secret themselves. Obviously this means that the communication of the Secret's name and namespace must happen out-of-band to the API though.

This is enforced by Contour itself; Contour still has permissions to read secrets anywhere, but you can grant RBAC access to the namespace where important Secrets live only to Contour and the people who need it.
