### ISSUE TITLE
Document security models

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/service-apis#115]
Currently,  different GatewayClass implementations by controllers can have wildy different security models.

This issue covers documenting some security models for different use cases, with the intent of being able to specify the security expectations various GatewayClass features would have.

For example, #111 adds a namespace to the Route reference inside the Gateway object. In some models, the Gateway object is higher privilege than the Routes, so it's okay to be able to have *any* namespace referenced here. However, in more self-service models, the namespace may need to be restricted to the current namespace or some other small set.

This is a decision made by the controller that implements the GatewayClass, and so is a property of the GatewayClass.

Deliverable for this ticket:
- Specification of at least two security models, roughly analogous to #102 and #103, plus any others we can think of.
- Some thoughts about what feature flags GatewayClasses could have to make these differences in behaviour clear by inspection of the GatewayClass.

**Comment by jpeach** [comment]
Prior art in this area
* Avi Networks `AviPolicyBinding`
* Contour root namespaces

**Comment by jpeach** [comment]
Note that this has significant implications on workload portability.

If gateway classes don't have the same rules around resolving object references, then it won't be possible for users to take a workload and simply switch gateway class. Operators will be required to write different access policies for different gateway classes.

There are two initial levels of portability that spring to mind:
1. Portable results (when it doesn't work, you can portably know that)
1. Portable API (there is a portable Policy API you can use to cover common case)

Not that for (1) we also have the negative policy problem, where you had a secure configuration, but changed gateway classes and now it is no longer secure. Since the config still works, there's no way to know you broke it. This issue seems hard to tackle without portable policy.

**Comment by jpeach** [comment]
ref #60

**Comment by danehans** [comment]
@youngnick here are a few xref's that may help you doc the sec model:

[example drawing](https://docs.google.com/drawings/d/1geL91ejvezuYpYW65aRfy8yghcdYAZ7fukN8GNUluVk/edit) and associated [rbac permissions](https://gist.github.com/danehans/daa49cac8e6fb72f96fd280bb9ac2945)
