### ISSUE TITLE
Make verify check that the kubebuilder generated code is up to date

### ISSUE THREAD

**Issue by bowei** [kubernetes-sigs/service-apis#14]
kubebuilder generates files so we should make sure they are always consistent w/ the source.

**Comment by Ravi19967** [comment]
\assign Ravi19967

**Comment by yiblet** [comment]
is this issue still open? If so I'd be interested in helping out.

**Comment by KaenDagger** [comment]
you can assign yourself by commenting "/assign"

**Comment by yiblet** [comment]
I can think of two different ways to make something that can verify whether to kubebuilder generated code is up to date.  One is hard, the other is easier. 

**The Hard**
make modifications to `controller-gen` to make it embed the hash of the files it processed for inside of it's generated output. Then, we can verify that the generated code is up to date based on whether or not the hash of in generated code matches the hash of the file. 

**The Easy**
Verify that the processed files last modify time occurs _before_ that of the generated files. This method requires a lot fewer code changes but can lead to false positives. 

I'm inclined to do the easier version because I'm not that familiar with `controller-gen`. However, the difficult part here is that I don't know exactly what set of files kubebuilder looks at. It seems like it's everything in `api/v1alpha1/` and `controllers/`. Can someone verify that this is the case?

**Comment by yiblet** [comment]
Scratch that. I found an even less intrusive (and hopefully more correct) way and set up the pull request #59
