### ISSUE TITLE
GatewayClass.Spec.ParametersRef is invalid as LocalObjectReference

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/service-apis#144]
Currently the field `GatewayClass.Spec.ParametersRef` is a `GatewayClassParametersObjectReference`, which aliases a custom type, `LocalObjectReference`. The documentation for `GatewayClassParametersObjectReference` states:

```golang
// GatewayClassParametersObjectReference identifies a parameters object for a
// gateway class within a known namespace.
```

Except the `LocalObjectReference` is only valid if the referrer is a namespaced object, and `GatewayClass` is scoped to the cluster.

**Comment by jpeach** [comment]
`GatewayClassParametersObjectReference` is now aliased to `ConfigMapsDefaultLocalObjectReference`, but the problem here is still present.

/remove-lifecycle rotten
/remove-lifecycle stale

**Comment by jpeach** [comment]
Ok I read the explanation in https://github.com/kubernetes-sigs/service-apis/pull/183#issuecomment-673109175. Sounds like the intention is that parameters reference here are also cluster-scoped. @robscott WDYT about updating the documentation here? Also, using `ConfigMapsDefaultLocalObjectReference` is still misleading because it would make people think that configmaps are intended to be used here.
