### ISSUE TITLE
Define or discuss lifetime coupling between Gateways and their GatewayClass

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#170]
When a GatewayClass is deleted, the spec does not address what happens to any Gateways that refer to that class.

I can think of 3 reasonable options:
1. Do nothing, orphaning the Gateways
2. Prevent the deletion of the GatewayClass while the class still owns Gateways
3. Delete all the owned Gateways as a side-effect

(1) is how many Ingress controllers work today, but the practical outcome is implementation-specific (cloud, on-prem and in-cluster implementations are all going to do something different)

(2) seems good from a UX perspective.

(3) seems like an explicable and consistent behavior, but potentially catastrophic UX

Maybe it's not necessary for the spec to define a single behavior as required. If so, then the spec should probably add some language to make it clear that implements can (and will) vary.

**Comment by bowei** [comment]
I think this can only be recommendations otherwise we may be imposing requirements for gateway controllers to watch gateways that are not explicitly managed (i.e. linked via gatewayclass field):

- API guarantee: no specific spec for behavior, user should not rely on behavior after gatewayclass deletion.
- Recommendation for controller authors: document behavior, use finalizers mechanism to manage lifetimes, fail gracefully to avoid disrupting customer traffic (fail static)

**Comment by akutz** [comment]
Hi @bowei,

> I think this can only be recommendations 

I think that is what @jpeach and I were suggesting anyway. I originally pinged James and @youngnick to solicit their advice based on their experience with `IngressClass`. James indicated this was a new-sh concern, and so at best I think we're just trying to define the best practice for the situation and document it so that readers:

* are aware of the issue
* are presented with some recommendations

**Comment by hbagdi** [comment]
#385 takes a stab at this. PTAL.

**Comment by hbagdi** [comment]
#385 was merged in.
Please re-open if this doesn't solve the problem.
/close
