### ISSUE TITLE
Support for v1alpha0

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/service-apis#231]
**What would you like to be added**:
I reached out to @robscott on Slack to ask when this project might lock/release v1alpha1 -- in other words, when will v1alpha1 no longer be a moving target, subject to possibly breaking changes? Rob indicated there has been discussion about possibly tagging v1alpha1 in Q3 or Q4 of this year (2020). Even though the project is still in alpha, the CRDs *are* useful, and there are reasons to use them. However, until v1alpha1 is locked, people are unable to safely leverage the CRDs from this project because v1alpha1 today may not be the same as v1alpha1 next week.

To that end I would like to propose one of the following:

* Create a branch `support/v1alpha0` from the project's main branch and set the schema version to `v1alpha0` on `support/v1alpha0`, or...
* Set the schema version to `v1alpha0` on the the project's main branch

In either case, there would be explicit messaging that:
* There is no support for `v1alpha0`
* There are no plans for any conversion webhooks for automated upgrade to `v1alpha1`. It would be on consumers of this project and its CRDs to provide these webhooks.

Both of the above solutions provide a clear upgrade path for resources created from the CRDs in the project today to resources based on `v1alpha1` when it is released. My personal preference is for the support branch because only it creates a _locked_ version of the project's CRDs. Setting the main branch to `v1alpha0`, while providing an upgrade path, still leaves us with a moving target.

**Why is this needed**:
VMware is leveraging this project's CRDs as a rally point for load balancer-related features. Our schedule is incongruent with the timeline for the Service APIs `v1alpha1` plan-of-record. Because we know others will also be targeting `v1alpha`, we want to avoid a situation where resources are created from CRDs based on `v1alpha1` as it is **today** and then others expect `v1alpha1` to represent the state of the CRDs when `v1alpha` is tagged later this year.

**Comment by robscott** [comment]
Thanks for starting this discussion! I think the current state of the repo is confusing at a minimum. We've been using the `v1alpha1` version despite not actually releasing a final `v1alpha1` API. Anyone browsing this repository could easily assume that this represents our `v1alpha1` release. I'd personally prefer transitioning to `v1alpha0` on the main branch until we actually reach a point we're ready to release as `v1alpha1`. 

I completely agree with your suggestions that `v1alpha0` would not be supported and that there would be no plans for any kind of conversion webhooks to upgrade to `v1alpha1`. This would effectively represent our pre-alpha work.

As far as providing a locked `v1alpha0` release, we could also explore creating a `v1alpha1` branch to contain the work towards the `v1alpha1` release, and leave `v1alpha0` alone but that could potentially get confusing as far as maintaining other areas such as the docs and the website. I'm not sure what the best approach here might be, but I'm hesitant to freeze/tag a release as `v1alpha0` since I don't think anything we have right now is particularly stable. Anything we froze at right now would feel rather arbitrary and not particularly representative of a proper API.

Maybe implementations that wanted to use `v1alpha0` could lock to a specific commit? At least by moving to `v1alpha0` CRDs it would be clearer that these are not part of a `v1alpha1` API, something that will actually be frozen when it is released. 

/cc @jpeach @danehans @bowei

**Comment by akutz** [comment]
Hi @robscott,

Thank you for such a fast and thoughtful response!

> Maybe implementations that wanted to use v1alpha0 could lock to a specific commit? At least by moving to v1alpha0 CRDs it would be clearer that these are not part of a v1alpha1 API, something that will actually be frozen when it is released.

To be super clear, it's not a commit issue so much as it is the CRDs. I agree that even setting the main branch to `v1alpha0` is better than what we have today, because this gives us a clear upgrade path from _something_ to `v1alpha1`. As it is, anyone publishing resources from today's CRDs are potentially in for a bad time when `v1alpha1` is finally tagged, because how do you go from `v1alpha1` to `v1alpha1`?

**Comment by bowei** [comment]
@akutz -- if we expect significant usage of the stuff that is public now, I would simply launch as `v1alpha2` (very little impact on all I would think)
Going backwards in time is pretty painful.
What do you think?

**Comment by robscott** [comment]
Sorry I missed following up on this one. I know we'd discussed it in a couple meetings when the issue was raised and likely also on Slack but unfortunately the conclusion never made it back here. If I'm remembering correctly, the suggestion was that a fork was more appropriate here since we couldn't find a precedent for a `v1alpha0` version. I could be missing some details on that. We're _very_ close to a final v1alpha1 release which should finally solve this with a usable API release outside of a fork or pinning to a commit.
