### ISSUE TITLE
Code generation was accidentally removed from makefile

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#296]
`make generate` should update generated code - it doesn't anymore. This immediate issue will be fixed by 
 https://github.com/kubernetes-sigs/service-apis/pull/263. Ideally a full fix would also tackle https://github.com/kubernetes-sigs/service-apis/issues/295.

**Comment by jpeach** [comment]
@robscott Can you post a PR with just the codegen fix so that we can land it immediately?

**Comment by jpeach** [comment]
OK I spent about an hour trying to get the `./hack/update-codegen` script to work. If you use Go modules (and don't put your git repo in the traditional $GOPATH location), it always outputs to the $GOPATH directory. In the past I've been able to get `controller-gen` to work correctly.

We probably should just switch back to `controller-gen` and ditch `update-codegen`. If you run each generator manually, I believe that they require different comment tags (`//+k8s` rather than `//+kubebuilder`), so it's confusing to do that.

I'll look at this more a bit later.

/assign
