### ISSUE TITLE
HostnameMatch should probably default to Domain instead of Exact

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#348]
@jpeach do you happen to remember if we had a reason for the `Exact` default here? I can't remember why we did this. More context here: https://github.com/kubernetes-sigs/service-apis/pull/336#discussion_r492272218.

**Comment by jpeach** [comment]
> @jpeach do you happen to remember if we had a reason for the `Exact` default here? I can't remember why we did this. More context here: [#336 (comment)](https://github.com/kubernetes-sigs/service-apis/pull/336#discussion_r492272218).

I think the defaults are correct as they are. If you omit the `Listener.Hostname` field, the default is "Any", which matches any requested hostname. If you specify this field, then the default for the struct is `Exact` so you only have so specify the exact hostname to match (I expect this to be the most common usage).

I don't think that we should default `HostnameMatch.Match` to "Any" because it's not the dominant use case, and we should optimize the YAML grammar so that the most common cases can be the most succinct.

**Comment by robscott** [comment]
I agree that `Any` doesn't make sense as a default here, but I can see an argument for `Domain` as a default. Do you think there's a compelling reason to choose `Exact` matching as the default instead of the more lenient `Domain` match?

**Comment by jpeach** [comment]
> I agree that `Any` doesn't make sense as a default here when a hostname is specified, but I can see an argument for `Domain` as a default. Do you think there's a compelling reason to choose `Exact` matching as the default instead of the more lenient `Domain` match?

Domain creates ambiguity with certificates (bad for operators) and encourages wildcards (bad for the ecosystem). I also expect that domain matching is also a less common need than exposing a specific hostname.

**Comment by robscott** [comment]
👍 That seems reasonable enough as long as we make it clear for users what our defaults are. I'll close this for now, anyone can feel free to reopen to discuss further.

**Comment by robscott** [comment]
Copying Daneyon and Harry before I resolve related feedback on API cleanup PR.

/cc @danehans @hbagdi
