### ISSUE TITLE
Finalize naming for Gateway resource

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#405]
This issue tracks the WG discussions that we have been having around renaming Gateway (and GatewayClass) resource.

Some early suggestions have been:
- AppGateway and AppGatewayClass [danehans]
- Router and RouterClass?
- AppProxy?

We are likely going to conduct a survey to settle on this.

/cc @robscott @jpeach @danehans

**Comment by bowei** [comment]
@robscott can you post the short link to the ideas doc?

**Comment by robscott** [comment]
[bit.ly/service-apis-naming](https://bit.ly/service-apis-naming)

**Comment by mark-church** [comment]
In an effort to actually start some name bikeshedding, I wanted to throw out some of my personal thoughts around ideas for Gateway naming and see what others thought. The [vote is still open](https://docs.google.com/forms/d/e/1FAIpQLSfgdecA_1UiriXIbITdROOcnbMa1pLEFivqXRQktik8nGHicg/viewform) and below is the final list of proposed names (which was cut down from the original list above): 

- Gateway
- AppGateway    
- Router    
- Portal    
- ServiceRouter    
- TrafficRouter    
- TrafficPortal

The consideration for re-naming the Gateway (and GatewayClass) resources started because of potential for overuse of the term - Istio already has a Gateway and there are also a lot of "API Gateway" products out there already. We could get to a place where you're saying "create a K8s Gateway resource for your [vendor] API Gateway controller that points at your Istio Gateway". 

Another thing I was wondering is how much Gateway makes sense for future potential use-cases of Service APIs. Let's say that we tried modeling gRPC clients in K8s using Service APIs. You could imagine that having a Gateway + GRPCRoute + Service could be used to define the service amongst gRPC clients. Except there is no real "gateway" here from a networking standpoint - it's client-side load balancing. Gateway can certainly be stretched in its meaning to "one or more ip:ports that's accepting traffic for your service” - it’s a broad enough term that this could work. Or alternatively, would we imagine that a separate resource would be used for non-middle-proxy use-cases?

Out of the other choices I do like “Router” the best:

* It’s even more generic than Gateway
* It’s not a compound word like the others which means less typing and verbosity
* It’s not very prevalent as a resource name in K8s (except for OpenShift of course)

I admit that neither Gateway nor any of the other terms really fit the strict networking definition for all of the use-cases we are fitting to the resource, but I don't think we are going to get to a perfect technical term for something this broad and that's okay. As the terms get used they take on their own meaning anyways.

What are everybody else's feelings on one name or another? Don't forget [to vote](https://docs.google.com/forms/d/e/1FAIpQLSfgdecA_1UiriXIbITdROOcnbMa1pLEFivqXRQktik8nGHicg/viewform) if you haven't already!

@robscott @jpeach @hbagdi @danehans @youngnick

**Comment by hbagdi** [comment]
@robscott conducted a survey and "Gateway" was deemed as the right name: https://docs.google.com/spreadsheets/d/18hlubHDfZ73oi17CmqmdL-fQOJiwrXLOFcbIU2RaTh0/edit#gid=779515090

We have also decided to rename Service APIs to Gateway APIs (#536).

/close
